Getting Started with Numpy

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
print(np.__version__)

1.18.5


Creating Numpy ndarray

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array(345)
print(arr)
print(type(arr))

345
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9]])
print(arr)
print(type(arr))

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9])]
<class 'numpy.ndarray'>


In [ ]:
arr=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(arr)
print(type(arr))

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
<class 'numpy.ndarray'>


In [ ]:
a=np.array(456)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
b=np.array([1,2,3,4,5])
print(b[2]+b[1])

5


In [ ]:
c=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(c)
print("Fifth element in 2nd dim",c[1,4])

[[1 2 3 4 5]
 [5 6 7 8 9]]
Fifth element in 2nd dim 9


In [ ]:
d=np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(d[1,0,1])
print(d.shape)

5
(3, 1, 3)


In [ ]:
c=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(c)
print("Last element in 2nd dim",c[1,-1])

[[1 2 3 4 5]
 [5 6 7 8 9]]
Last element in 2nd dim 9


In [ ]:
b=np.array([1,2,3,4,5])
print(b[1:3])

[2 3]


In [ ]:
b=np.array([1,2,3,4,5,6,7,8,9,10])
print(b[1:7:2])

[2 4 6]


In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[0:3,1:3])

[[2 3]
 [7 8]]


In [ ]:
c=np.array(['Manas','Jhon','Stark','Logan','Bruce','Charles'])
print(c)
print(c.dtype)

['Manas' 'Jhon' 'Stark' 'Logan' 'Bruce' 'Charles']
<U7


In [ ]:
b=np.array([1,2,3,4,5])
newarr=b.astype(str)
print(newarr)
print(newarr.dtype)

['1' '2' '3' '4' '5']
<U21


In [ ]:
b=np.array([1.2,2.3,3.4,4.5,5.6])
newarr=b.astype(int)
print(newarr.dtype)

int64


In [ ]:
b=np.array([1.2,2.3,3.4,4.5,5.6])
newarr=b.copy()
print(b)
print(newarr)
print(newarr.dtype)

[1.2 2.3 3.4 4.5 5.6]
[1.2 2.3 3.4 4.5 5.6]
float64


In [ ]:
b=np.array([1.2,2.3,3.4,4.5,5.6])
newarr=b.view()
print(b)
newarr[0]=34
print(b)
print(newarr)
print(newarr.dtype)

[1.2 2.3 3.4 4.5 5.6]
[34.   2.3  3.4  4.5  5.6]
[34.   2.3  3.4  4.5  5.6]
float64


In [ ]:
b=np.array([1.2,2.3,3.4,4.5,5.6])
x=b.view()
y=b.copy()
print(x.base)
print(y.base)

[1.2 2.3 3.4 4.5 5.6]
None


In [ ]:
b=np.array([1.2,2.3,3.4,4.5,5.6,7.7])
newarr=b.reshape(2,3,1)
print(newarr)

[[[1.2]
  [2.3]
  [3.4]]

 [[4.5]
  [5.6]
  [7.7]]]
